org: ianfs
service: async-report

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  memorySize: 128
  environment:
    DYNAMO_LEADS_TABLE: !Ref LeadsTable
    GENERATE_REPORT_QUEUE_URl: !Ref GenerateReportQueue
    REPORTS_BUCKET_NAME: !Ref ReportsBucket
  iam:
    role:
      statements:
        # Dynamo
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:scan
          Resource: !GetAtt LeadsTable.Arn
        #SQS
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: !GetAtt GenerateReportQueue.Arn
        #S3
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:AbortMultipartUpload
          Resource: !Join ['/', [!GetAtt ReportsBucket.Arn, '*']]

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  populateDynamo:
    handler: src/functions/http/populateDynamo.handler
    timeout: 25
    events:
      - httpApi:
          path: /populate-dynamo
          method: POST

  generateReport:
    handler: src/functions/http/generateReport.handler
    events:
      - httpApi:
          path: /generate-report
          method: POST

  processReport:
    handler: src/functions/queues/processReport.handler
    timeout: 180
    memorySize: 512
    events:
      - sqs:
          arn: !GetAtt GenerateReportQueue.Arn
          batchSize: 1

resources:
  - ${file(./resources/dynamodb/LeadsTable.yml)}
  - ${file(./resources/sqs/GenerateReportQueue.yml)}
  - ${file(./resources/s3/ReportsBucket.yml)}
